### ISSUE TITLE
Meridian 59 serverless?

### ISSUE THREAD

**Issue by communityus** [brianclaridge/serverless-examples#1]
I happened on your repos from the Meridian 59 bible static site. Excited to check this out. Then when I saw serverless examples I had to ask if you ever thought about spinning up a MUD server for meridian in docker and adding it here?

https://github.com/Meridian59/Meridian59/wiki/Build-Instructions
https://github.com/OpenMeridian105/Meridian59

also there is a server 112 mentioned here:
https://github.com/cyberjunk/meridian59-dotnet

but i have not found it yet.

**Comment by brianclaridge** [comment]
I have not -- but that could be a lot of fun.

**Comment by communityus** [comment]
I forget where my train of thought was when I posted the idea. I think it was on using the dot net meridian from cyberjunk in a dot net docker container. I know with dot net 3.0 in preview a lot of previous road blocks have been removed.
